import { Inter, Anton } from "next/font/google";
import "./globals.css";
import SmoothScroller from "@/components/SmoothScroller";

const inter = Inter({ subsets: ["latin"] });
const anton = Anton({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--heading-font",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head />
			<body
				className={`${inter.className} ${anton.variable} overflow-x-hidden`}
			>
				<SmoothScroller>{children}</SmoothScroller>
			</body>
		</html>
	);
}
