/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/scene.gltf --transform 
Files: ./public/models/scene.gltf [18.82KB] > C:\MyCode\studio-eg\scene-transformed.glb [897.28KB] (-4668%)
Author: Erdem Dağdelen (https://sketchfab.com/erdemdagdelen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arcade-machine-69409b165c2c418c8f78a5b32cec5c02
Title: Arcade Machine
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/models/scene.glb");
	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.defaultMaterial.geometry}
				material={materials.material}
				position={[0, -0.041, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<mesh
				geometry={nodes.defaultMaterial_1.geometry}
				material={materials.screw}
				position={[-265.749, 109.435, -341.508]}
				rotation={[-Math.PI / 2, 0, -0.252]}
				scale={[6.848, 17.818, 5.57]}
			/>
			<mesh
				geometry={nodes.defaultMaterial_2.geometry}
				material={materials.cable}
				position={[-265.749, 109.435, -341.508]}
				rotation={[-Math.PI / 2, 0, -0.252]}
				scale={[6.848, 17.818, 5.57]}
			/>
			<mesh
				geometry={nodes.defaultMaterial_3.geometry}
				material={materials.priz}
				position={[-265.749, 109.435, -341.508]}
				rotation={[-Math.PI / 2, 0, -0.252]}
				scale={[6.848, 17.818, 5.57]}
			/>
			<mesh
				geometry={nodes.defaultMaterial_4.geometry}
				material={materials.Kablo}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<mesh
				geometry={nodes.defaultMaterial_5.geometry}
				material={materials.joystick}
				position={[-265.749, 109.435, -341.508]}
				rotation={[-Math.PI / 2, 0, -0.252]}
				scale={[6.848, 17.818, 5.57]}
			/>
			<mesh
				geometry={nodes.defaultMaterial_6.geometry}
				material={materials.game}
				position={[-265.749, 109.435, -341.508]}
				rotation={[-Math.PI / 2, 0, -0.252]}
				scale={[6.848, 17.818, 5.57]}
			/>
			<mesh
				geometry={nodes.defaultMaterial_7.geometry}
				material={materials.Base}
				position={[0, -0.041, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
		</group>
	);
}

useGLTF.preload("/models/scene.glb");
